### ISSUE TITLE
TestClassMustBeProperlyNamedRule support for junit jupiter

### ISSUE THREAD

**Issue by icenfrosty** [OpenPojo/openpojo#127]
From:

package com.openpojo.validation.rule.impl;
public class TestClassMustBeProperlyNamedRule implements Rule {
  public static final String DEFAULT_ANNOTATIONS[] = { "org.testng.annotations.Test", "org.junit.Test" };

To:

	public static final String DEFAULT_ANNOTATIONS[] = { "org.testng.annotations.Test", "org.junit.Test", "org.junit.jupiter.api.Test" };

**Comment by oshoukry** [comment]
Thank you very much, please upgrade to release 0.8.11, change included.
