### ISSUE TITLE
Tutorial 1. Getting Started page provide an examples using deprecated class PojoValidator

### ISSUE THREAD

**Issue by IharReznichenka** [OpenPojo/openpojo#134]
Currently a Getting Started page uses Deprecated class which may be a bit misleading for new users. It would be nice to provide a proper way from the very beginning. 
A Java code examples could be updated with an example using ValidatorBuilder.

``` Java
public class PersonTest {
  @Test
  public void validateSettersAndGetters() {
		PojoClass personPojo = PojoClassFactory.getPojoClass(Person.class);
		Validator validator = ValidatorBuilder.create()
				// Lets make sure that we have a getter and a setter for every field defined.
				.with(new SetterMustExistRule())
				.with(new GetterMustExistRule())
				// Lets also validate that they are behaving as expected.
				.with(new SetterTester())
				.with(new GetterTester())
				.build();

		// Start the Test
		validator.validate(personPojo);
  }
}
```

I'm really sorry for posting it as an issue. Unfortunately I'm not aware of a proper way how to submit a pull request for Wiki pages.

**Comment by oshoukry** [comment]
Thank you for the note, I have updated the wiki page.
