### ISSUE TITLE
SetterMustExist Not Ignoring Synthetic Fields

### ISSUE THREAD

**Issue by scampbell5** [OpenPojo/openpojo#139]
Hello,

We use this library alongside of pitest for mutation checks. Recently we have upgraded to pitest >= 1.6.2 which now currently fails to run mutation coverage because when pitest injects their private field probes into the classes that openpojo is testing against, it's causing it to fail due to it not finding a setter for these synthetic fields. I opened an issue in the pitest plugin here: https://github.com/hcoles/pitest/issues/873. Their suggestion was to have openpojo ignore synthetic fields. I noticed for the Getter rule, that was already in place: https://github.com/OpenPojo/openpojo/releases/tag/openpojo-0.8.6, but not the for SetterMustExistRule. I created a PR to fix this issue: https://github.com/OpenPojo/openpojo/pull/138

**Comment by mustaphazorgati** [comment]
@OrDTesters, @oshoukry,

can you please have a look at this? I think this is a very quick one :)

**Comment by oshoukry** [comment]
issue fixed and released see latest release.

**Comment by mustaphazorgati** [comment]
:clap: Thank you very much. Works like a charm
