### ISSUE TITLE
NoStaticExceptFinalRule should skip synthetic fields

### ISSUE THREAD

**Issue by mustaphazorgati** [OpenPojo/openpojo#140]
along with #88 and #139 the NoStaticExceptFinalRule should also skip synthetic field so that the user don't have to duplicate that class when using something like AspectJ.

**Comment by mustaphazorgati** [comment]
@OrDTesters, @oshoukry,

can you please have a look at this? I think this is a very quick one :)

**Comment by oshoukry** [comment]
issue fixed and released see latest release.

**Comment by mustaphazorgati** [comment]
:clap: Thank you very much. Works like a charm
